version: "3"
services:
  web:
    build:
      context: ./build-web
    image: app:v1
    ports:
      - 8080:80
    volumes:
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: simple_lamp
    volumes:
      - ./simple_lamp:/docker-entrypoint-initdb.d
      - dbb:/var/lib/mysql
   ports:
      - 3306:3306
volumes:
  dbb:
