- hosts: srv
  become: yes
  tasks:
    - name: add repo
      apt_repository:
        repo: deb https://mirror.yandex.ru/debian bullseye main contrib non-free
        state: present
    - name: Install packages
      apt:
        pkg:
          - docker
          - docker.io
          - docker-compose
          - curl
          - apparmor
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
    - name: Install caddy key
      shell: |
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    - name: Install caddy repo
      get_url: 
        url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
        dest: /etc/apt/sources.list.d/caddy-stable.list
    - name: apt update and install caddy
      apt:
        update_cache: yes
        pkg: caddy
    - name: Start caddy
      service:
        name: caddy
        state: started
        enabled: yes
    - name: Copy caddy config
      copy:
         src: Caddyfile
         dest: /etc/caddy/Caddyfile      
    - name: Restart caddy
      service:
        name: caddy
        state: restarted
    - name: Copy dir
      copy:
        src: ./lamp
        dest: /home/debian/
    - name: Permission
      file:
        path: /home/debian/lamp/uploads
        owner: www-data
    - name: Start docker-compose
      docker_compose:
        project_src: /home/debian/lamp
          
