- hosts: srv
  become: yes
  tasks:
    - name: add repo
      apt_repository:
        repo: deb https://mirror.yandex.ru/debian bullseye main contrib non-free
        state: present
    - name: Install packages
      apt:
        pkg:
          - docker
          - docker.io
          - docker-compose
          - curl
          - apparmor
    - name: Create project dir
      file:
        path: /home/debian/wordpress
        state: directory 
    - name: Install Caddy
      shell: |
        sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        sudo apt update
        sudo apt install caddy
    - name: Start caddy
      service:
        name: caddy
        state: started
        enabled: yes
    - name: Copy caddy config
      copy:
         src: Caddyfile
         dest: /etc/caddy/Caddyfile      
    - name: Restart caddy
      service:
        name: caddy
        state: restarted
    - name: Copy docker-compose
      copy:
        src: docker-compose.yaml
        dest: /home/debian/wordpress/docker-compose.yaml
    - name: Start docker-compose
      docker_compose:
        project_src: /home/debian/wordpress
          
